name: CI .NET

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.300
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
